name: typo3-sentry-client
type: typo3
docroot: .build/web
php_version: "8.0"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
mysql_version: ""
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - PATH=/var/www/html/.build/bin:$PATH
  - TYPO3_CONTEXT=Development
